const initialValue = {
  name: '',
  last_name: null,
  first_name: null,
  middle_name: null,
  certificate: null,
  date_certificate_start: null,
  date_certificate_stop: null,
  date_certificate_renew: null,
  qualification: null,
  high_education: [],
  date_membership_start: null,
  date_membership_stop: null,
  date_membership_exclusion: null,
  insurance: null,
  insurance_serial_num: null,
  date_insurance_from: null,
  date_insurance_start: [],
  date_insurance_stop: null,
  period_insurance_start: [],
  period_insurance_stop: null,
  liability_limit: null,
  currency: null,
  organization: null,
  unp: null,
  registration_region: null,
  registration_city: null,
  is_consultant: false,
  phone: null,
  email: null,
  url: null,
  legal_entity_services: [],
  entrepreneurs_services: [],
  personal_services: [],
  is_hidden: false,
};

export default initialValue;
