export default Object.freeze({
  siteUrl: '',
  certificate: '',
  dateCancellation: '',
  dateEntry: '',
  dateException: '',
  dateIssue: '',
  dateMembership: '',
  dateRenewal: '',
  email: '',
  firstName: '',
  lastname: '',
  phoneNumber: '',
  shureName: '',
  qualifications: [],
  education: [],
  provideServicesTaxConsultant: false,
  legalEntities: [],
  individualEntrepreneurs: [],
  individualPerson: [],
  insuranceContract: {
    number: '',
    series: '',
    date: '',
    validity: [],
    term: [],
    liabilityLimit: '',
    currency: '',
  },
  placeOfWork: {
    companyName: '',
    unp: '',
    city: '',
    region: '',
  }
})