const initialValue = {
  name: "",
  first_name: "",
  middle_name: null,
  last_name: "",
  certificate: null,
  date_certificate_start: null,
  date_certificate_stop: null,
  date_certificate_renew: null,
  qualification: '',
  high_education: ['checked-2'],
  date_membership_start: null,
  date_membership_stop: null,
  date_membership_exclusion: '',
  insurance: null,
  insurance_serial_num: null,
  date_insurance_from: null,
  date_insurance_start: [],
  period_insurance_start: [],
  liability_limit: null,
  currency: '',
  organization: null,
  unp: null,
  registration_region: null,
  registration_city: null,
  is_consultant: false,
  phone: null,
  email: "",
  url: null,
  legal_entity_services: null,
  entrepreneurs_services: null,
  personal_services: null,
};

export default initialValue;
